father(Father, Child) :-
    begat(Father, Child).

ancestor_of(Ancestor, Descendant) :-
    begat(Ancestor, Descendant).

ancestor_of(Ancestor, Descendant) :-
    father(Ancestor, Descendant).

ancestor_of(Ancestor, Descendant) :-
    begat(Ancestor, Parent),
    ancestor_of(Parent, Descendant).

ancestor_of(Ancestor, Descendant) :-
    father(Ancestor, Parent),
    ancestor_of(Parent, Descendant).
